apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: shpagin/sampleapp
  newName: shpagin/sampleapp
  newTag: newsampleapp

resources:
- deployment.yml
- service.yml
- postgres-deployment.yml
- postgres-service.yml
- secret.yml
