apiVersion: v1
data:
  PORT: NTAwMA==
  POSTGRES_DB: aGVsbG9fZmxhc2tfcHJvZA==
  POSTGRES_HOST: c2hwYWdpbi1kZXZvcHMtZmluYWwtdGFzay1zZXJ2aWNlLXBvc3RncmVzLnNocGFnaW4tZGV2b3BzLWZpbmFsLXRhc2suc3ZjLmNsdXN0ZXIubG9jYWw=
  POSTGRES_PASSWORD: aGVsbG9fZmxhc2s=
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: aGVsbG9fZmxhc2s=
kind: Secret
metadata:
  name: shpagin-devops-final-task-postgres-secret
