apiVersion: v1
kind: Service
metadata:
  name: final_task_app-service
spec:
  selector:
    app: final_task_app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP