apiVersion: v1
kind: Service
metadata:
  name: shpagin-devops-final-task-service
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: shpagin-devops-final-task
  type: ClusterIP