apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shpagin-namespace
images:
  - name: nginx
    newName: nginx
    newTag: 1.23.2-alpine
  - name: cxcxmbxr/final_task_app
    newTag: main



resources:
- ../../base
- ingress.yaml
- namespace.yaml
- certificate.yaml