apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: final-task-image
    newName: shpagin-devops-final-task
    newTag: v1.1.1

resources:
- ../../base
- ingress.yaml
- namespace.yaml
- certificate.yaml