apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shpagin-devops-final-task
  name: shpagin-devops-final-task-deployment-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shpagin-devops-final-task
  template:
    metadata:
      labels:
        app: shpagin-devops-final-task
    spec:
      containers:
      - env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        envFrom:
        - secretRef:
            name: shpagin-devops-final-task-postgres-secret
        image: postgres:15.1
        name: postgres
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 256Mi