apiVersion: v1
kind: Service
metadata:
  labels:
    app: shpagin-devops-final-task
  name: shpagin-devops-final-task-service-postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: shpagin-devops-final-task
  type: ClusterIP